In [2]:
### These all notes are made by Gibran Khan Tareen. I have made it for other student's reference and also for my personal revision ###

# Notes Begins below #

# NumPy is a Python library used for big mathematical functions

## NUMPY Full form is Numerical Python
## NUM = NUMerical 
## PY = PYthon

# To use Numpy library we will first have to import it
## Syntax => import numpy as aliasname

import numpy as np 

In [8]:
# How will I create an Array with Numpy?

## Syntax => nameofarray = np.array([value1,value2,...])

### IMP- Whenever we do INDEXING, SLICING and LISTs we will be using Square Brackets []

gibran_ka_array = np.array([1,2,3])
gibran_ka_array

array([1, 2, 3])

In [7]:
# What will I do if I want to Create an output like below:
## 1  2  3
## 4  5  6
## 7  8  9

# Normal array is like [val1 , val2 , val3 ....]
# The concept which we will use for it is of "List inside List". Means we will make an array but we are making each array-item a seperate list

## Syntax => arrayname = [[val1, val2, val3] , [val4, val5, val6], [val7,val8,val9]] {As mentioned above, for making Lists we use []}

gibran_list_ki_list = [[1,2,3],[4,5,6],[7,8,9]]
gibran_list_ki_list


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
# Numpy's arange function

# Yes it is not a typing mistake. 
## This function is written as 'arange' not arrange. 'arange' means "a range" or an interval.
### Its very simple. As the name suggests, it is used to get a range of values 

### Syntax => np.arange(starting_value, stop_value, step) 

# IMP Points: 
## 'starting_value' is the "Lower Limit" or a value from which our range starts. By default it is 0
## 'stop_value' is the "Upper limit" or the ending value which you want to keep for your range
## "step" refers to the size of interval which we want to keep between the start value and ending value. Default step value is 1

# VERY IMP=> If I say np.arange(1,5) it simply means Range of numbers "BETWEEN" 1 to 5. Which simply means 1, 2, 3, 4 and NOT INCLUDING 5 (between means beechme)

# Those who did not understand the 'between' concept or WHY do we NOT include the STOP_VALUE also, it can be understood by the example given below.
## If I start a journey from Ludhiana to Delhi. To complete my I will have to I travell accross Ludhiana, Sirhind, CityX, CityY, CityZ and finally reach Delhi. 
## On arriving Delhi I will go to my hotel my journey will get STOPPED. 
## So can I say that on my journey from Ludhiana to Delhi, I have travelled accross DELHI also?? Answer is NO.
## That is why we do not include the last ENDING_VALUE in np.arrange()

np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
### Numpy's np.arange() function with a STEP

## If i write np.arange(1,10, 2) this simply means it will get me a range of numbers between 1 and 10 (including 1 and excluding 10 as explained above)
## What STEP will do in this, it will start from START_VALUE = 1 and till before 10, and the generate more numbers with a spacing of 2 between the values.
## Which means 1, 1+2, 1+2+2, 1+2+2+2 and 1+2+2+2+2 ; All of which will be < 10

np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [16]:
# Numpy's np.zeros() function

## This function is used to get number of zeros are given in the parameter
## IMP => Output of 0s by default is of FLOAT Datatype

# SYNTAX => np.zeros(5) will generate 5 0s

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
### If I do not want FLOAT in np.zeros() function

## For this I just need to give "int" as a parameter

# SYNTAX=> np.zeros(5,INT) or np.zeros(5, dtype=int)

np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [19]:
# Numpy's np.ones() function

## Similar to np.zeros(), this function is used to get number of 'ones' are given in the parameter
## IMP => Output of 1(s) by default is of FLOAT Datatype

np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
### If I do not want FLOAT in np.ones() function

## Similar to np.zeros() for this I just need to give "int" as a parameter

# SYNTAX=> np.ones(5,int) or np.zeros(5, dtype=int)

np.ones(5,int)

array([1, 1, 1, 1, 1])

In [25]:
#### If i want to create an array of zeros but in 2 rows and 3 columns

# SYNTAX=> np.zeros((num_of_rows, num_of_columns))

np.zeros((2,3),int)


array([[0, 0, 0],
       [0, 0, 0]])

In [26]:
#
#
#

In [36]:
## Numpy's Linspace() function

# np.linspace() function is used to get numbers spaced evenly as per the given interval

# SYNTAX => np.linespace(START, END, NUM) ; here NUM is total how many numbers you want to generate 
## If we do not declare NUM value, default value is 50 ie. it will divide given range to 50 parts
## In np.linspace(), END value is also included
## INSHORT it is used to divide the Range (example. from 1 to 5 into X equal parts) {Let NUM = X}

np.linspace(1, 5, 10) #It divides the range from 1 and 5 into 10 equal parts. They are Equally spaced 1.0, 1.0 + 0.4444, 1.0 + 0.4444 + 0.4444 ...... till 5.0

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [37]:
#
#

In [41]:
# Numpy's np.eye() function

## Stands for Identity matrix

# SYNTAX => np.eye(num_of_rows, C)

# Note: C stands for no. of columns. By default C (Num_of_Columns) = Num_of_rows 
## Inshort what np.eye() does it, it generates a 2D array with 0 and 1s accross R x C values.
## IMP=> In this, we have 1st value as 1, then in 2nd row 2nd value as one.... so on till we have a diagonal of 1s

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])